[package]
name = "facerecognition-opencvjs"
version = "0.1.0"
authors = ["Adiguna7 <sevensag@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustface = "0.1.6"
image = "0.23.12"
